_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.9.12
        t:
            "1":
                - 1
                - 50
                - 55
                - 79
            "2":
                - 1
                - 50
                - 55
                - 79
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
