project_name: 'plastic'
entity: 'k1seul_davian'
group_name: 'ddqn_injection'
exp_name: '25M_injection'
device: cuda:0
seed: 0

defaults:
- _self_
- agent: plastic_injection
- env: atari
- model: plastic_injection